# this pipeline yaml is triggered due to the branch policy in azure DevOps repos 

name: '$(FeatureBranchName).$(Build.BuildId)'

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  project: 'GovX.Customers.Rpc.ServerHost'
  repository: 'govx-customers-rpc'
  FeatureBranchName: $[replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '')]

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 6.0.201
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: Run Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'd82ba27b-a9c1-41f8-b3d4-0b79f632133f'
      verbosityRestore: 'Diagnostic'

  - task: DotNetCoreCLI@2
    displayName: "Run Publish "
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/$(project).csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)/root --no-restore'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      containerRegistry: crgxdev
      command: login

  - task: Docker@2
    displayName: Build and Push to ACR
    inputs:
      containerRegistry: 'govxdev-cr'
      repository: '$(repository)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(FeatureBranchName).$(Build.BuildId)'

  - task: Bash@3
    displayName: Write release config to drop
    inputs:
      targetType: 'inline'
      script: 'echo "$(FeatureBranchName).$(Build.BuildId)" > $(build.artifactstagingdirectory)/root/release.config'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact to Release'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/root/release.config'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    condition: succeededOrFailed()
    